-- MySQL Script generated by MySQL Workbench
-- 14 ديس, 2022 05:22:26 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Shorty
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Shorty
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shorty` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Shorty` ;

-- -----------------------------------------------------
-- Table `Shorty`.`_prisma_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shorty`.`_prisma_migrations` (
  `id` VARCHAR(36) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  `migration_name` VARCHAR(255) NOT NULL,
  `logs` TEXT NULL DEFAULT NULL,
  `rolled_back_at` DATETIME(3) NULL DEFAULT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `applied_steps_count` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Shorty`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shorty`.`user` (
  `id` VARCHAR(191) NOT NULL,
  `username` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `followers` INT NOT NULL DEFAULT '0',
  `following` INT NOT NULL DEFAULT '0',
  `posts` INT NOT NULL DEFAULT '0',
  `photo` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `details` VARCHAR(191) NULL DEFAULT '',
  `photoId` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_email_key` (`email` ASC) VISIBLE,
  FULLTEXT INDEX `user_username_idx` (`username`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Shorty`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shorty`.`video` (
  `id` VARCHAR(191) NOT NULL,
  `details` VARCHAR(191) NOT NULL,
  `likes` INT NOT NULL DEFAULT '0',
  `comments` INT NOT NULL DEFAULT '0',
  `url` VARCHAR(191) NOT NULL,
  `thumbnail` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `thumbnailId` VARCHAR(191) NOT NULL,
  `urlId` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `video_userId_fkey` (`userId` ASC) VISIBLE,
  FULLTEXT INDEX `video_details_idx` (`details`) VISIBLE,
  CONSTRAINT `video_userId_fkey`
    FOREIGN KEY (`userId`)
    REFERENCES `Shorty`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Shorty`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shorty`.`comment` (
  `id` VARCHAR(191) NOT NULL,
  `details` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `videoId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `comment_userId_fkey` (`userId` ASC) VISIBLE,
  INDEX `comment_videoId_fkey` (`videoId` ASC) VISIBLE,
  CONSTRAINT `comment_userId_fkey`
    FOREIGN KEY (`userId`)
    REFERENCES `Shorty`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `comment_videoId_fkey`
    FOREIGN KEY (`videoId`)
    REFERENCES `Shorty`.`video` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Shorty`.`followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shorty`.`followers` (
  `followingId` VARCHAR(191) NOT NULL,
  `beenFollowingId` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`beenFollowingId`, `followingId`),
  INDEX `followers_followingId_fkey` (`followingId` ASC) VISIBLE,
  CONSTRAINT `followers_beenFollowingId_fkey`
    FOREIGN KEY (`beenFollowingId`)
    REFERENCES `Shorty`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `followers_followingId_fkey`
    FOREIGN KEY (`followingId`)
    REFERENCES `Shorty`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Shorty`.`likedVideo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shorty`.`likedVideo` (
  `userId` VARCHAR(191) NOT NULL,
  `videoId` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`userId`, `videoId`),
  INDEX `likedVideo_videoId_fkey` (`videoId` ASC) VISIBLE,
  CONSTRAINT `likedVideo_userId_fkey`
    FOREIGN KEY (`userId`)
    REFERENCES `Shorty`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `likedVideo_videoId_fkey`
    FOREIGN KEY (`videoId`)
    REFERENCES `Shorty`.`video` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Shorty`.`notificationMessage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shorty`.`notificationMessage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `messageDetail` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Shorty`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shorty`.`notification` (
  `id` VARCHAR(191) NOT NULL,
  `messageId` INT NOT NULL,
  `videoId` VARCHAR(191) NULL DEFAULT NULL,
  `seen` TINYINT(1) NOT NULL DEFAULT '0',
  `triggerId` VARCHAR(191) NOT NULL,
  `notifierId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `notification_messageId_fkey` (`messageId` ASC) VISIBLE,
  INDEX `notification_videoId_fkey` (`videoId` ASC) VISIBLE,
  INDEX `notification_triggerId_fkey` (`triggerId` ASC) VISIBLE,
  INDEX `notification_notifierId_fkey` (`notifierId` ASC) VISIBLE,
  CONSTRAINT `notification_messageId_fkey`
    FOREIGN KEY (`messageId`)
    REFERENCES `Shorty`.`notificationMessage` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `notification_notifierId_fkey`
    FOREIGN KEY (`notifierId`)
    REFERENCES `Shorty`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `notification_triggerId_fkey`
    FOREIGN KEY (`triggerId`)
    REFERENCES `Shorty`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `notification_videoId_fkey`
    FOREIGN KEY (`videoId`)
    REFERENCES `Shorty`.`video` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
